"""Configuration file for nmea-mqtt-py

    DO NOT EDIT THIS FILE!

Instead, copy it to config.py, then edit the copy.
     cp config-sample.py config.py
     nano config.py
"""

# Set to 1 for debug messages
DEBUG = 0

# Settings related to the NMEA socket connection
NMEA_HOST = "localhost"
NMEA_PORT = 10110
NMEA_TIMEOUT = 20
NMEA_RETRY_WAIT = 60

# How often, in seconds, to write a record to the SQLITE file
WRITE_INTERVAL = 10

# SQLITE info
SQLITE_FILE = "/var/tmp/wf_log.sdb"
SQLITE_SCHEMA = """CREATE TABLE archive (timestamp INTEGER NOT NULL UNIQUE PRIMARY KEY, 
            latitude REAL, longitude REAL, depth REAL, distance REAL);"""
